services:
  bot:
    build: .
    restart: always
    container_name: shwork_bot  # O'zgartirilgan nom
    environment:
      BOT_TOKEN: 7718632127:AAEOND5R0e6XJgFZ7mMVXv2dY8rbL3jZrzI #bot token
      DB_NAME: bot #databasedai nomga o'zgaradi
      DB_PASSWORD: 1
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 main.py

  pg:
    image: postgres
    restart: always
    container_name: shwork_pg  # O'zgartirilgan nomp
    environment:
      DB_NAME: bot  # Create the database automatically
      DB_USER: postgres
      DB_PASSWORD: 1

    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
