
services:
  bot:
    build: .
    restart: always
    container_name: shwork_bot  # O'zgartirilgan nom
    environment:
      BOT_TOKEN: 7318906816:AAGIdwRjL3tJwodaxSZI1OPGpRpYUpy2m2I
      DB_NAME: shwork
      DB_PASSWORD: 1
      DB_HOST: localhost
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 main.py

  pg:
    image: postgres
    restart: always
    container_name: shwork_pg  # O'zgartirilgan nomp
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
